AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  RTStockLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: realtime_stock_quote.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::989073812644:role/service-role/RTStockLambda-role-ngs7u99f'
      Layers:
        - >-
          arn:aws:lambda:us-east-1:989073812644:layer:python-selenium-chrome-layer:2
